# Generated by Django 4.2.6 on 2023-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("age", models.IntegerField(verbose_name="Idade")),
                (
                    "first_semester_grade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nota do primeiro semestre",
                    ),
                ),
                (
                    "second_semester_grade",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Nota do segundo semestre",
                    ),
                ),
                (
                    "professor_name",
                    models.CharField(max_length=100, verbose_name="Nome do professor"),
                ),
                (
                    "room_number",
                    models.CharField(max_length=10, verbose_name="Número da sala"),
                ),
            ],
            options={
                "verbose_name": "Estudante",
                "verbose_name_plural": "Estudantes",
            },
        ),
    ]
