# Generated by Django 4.2.6 on 2023-10-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="age",
            new_name="idade",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="name",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="professor_name",
            new_name="nome_do_professor",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="first_semester_grade",
            new_name="nota_do_primeiro_semestre",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="second_semester_grade",
            new_name="nota_do_segundo_semestre",
        ),
        migrations.RemoveField(
            model_name="student",
            name="room_number",
        ),
        migrations.AddField(
            model_name="student",
            name="numero_da_sala",
            field=models.IntegerField(default=1, verbose_name="Número da sala"),
            preserve_default=False,
        ),
    ]
