databases:
  - name: potencia-tech
    databaseName: potencia_tech
    user: potencia_tech_user

services:
  - type: web
    name: django-potencia-tech
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: potencia-tech
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
