name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim-buster

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Dependencies and run Migrations
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Render Deployment
      uses: sws2apps/render-deployment@v1.6.0
      with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false
            
